// Generated by https://quicktype.io

export interface DataUserInfoProps {
  profile_picture_url: null
  id: number
  shop_id: number
  df_type_user_id: number
  user_name: string
  full_name: string
  token: string
  last_login_date: string
  reset_password: null
  expired_reset_password: null
  device_id: null
  name: string
  phone: string
  email: string
  referal_customer_id: null
  point: number
  status: number
  date_of_birth: null
  gender: null
  is_active: number
  create_at: string
  update_at: string
  delete_at: null
  type_user_name: string
  Shop: Shop
  UserAddresses: any[]
  livestream_enable: number
}

export interface Shop {
  profile_picture_url: null
  id: number
  name: string
  phone: string
  livestream_enable: number
  status: number
  stream_minutes_available: number
}
