import I18n from '@app/i18n/i18n'
function strings() {
  return {
    cancel: I18n.t('cancel', { defaultValue: '' }),
    confirm: I18n.t('confirm', { defaultValue: '' }),
    notification: I18n.t('notification', { defaultValue: '' }),
    re_login: I18n.t('re_login', { defaultValue: '' }),
    try_again: I18n.t('try_again', { defaultValue: '' }),
    account: I18n.t('account', { defaultValue: '' }),
    loading_progress: I18n.t('loading_progress', { defaultValue: '' }),
    login: I18n.t('login', { defaultValue: '' }),
    forgotPass: I18n.t('forgotPass', { defaultValue: '' }),
    sign_up: I18n.t('sign_up', { defaultValue: '' }),
    mail_sign_up: I18n.t('mail_sign_up', { defaultValue: '' }),
    send: I18n.t('send', { defaultValue: '' }),
    otp_mess: I18n.t('otp_mess', { defaultValue: '' }),
    network_error: I18n.t('network_error', { defaultValue: '' }),
    home: I18n.t('home', { defaultValue: '' }),
    noti: I18n.t('noti', { defaultValue: '' }),
    profile: I18n.t('profile', { defaultValue: '' }),
    password: I18n.t('password', { defaultValue: '' }),
    re_password: I18n.t('re_password', { defaultValue: '' }),
    in_email: I18n.t('in_email', { defaultValue: '' }),
    inp_phone: I18n.t('inp_phone', { defaultValue: '' }),
    inp_username: I18n.t('inp_username', { defaultValue: '' }),
    pass_error: I18n.t('pass_error', { defaultValue: '' }),
    er_login: I18n.t('er_login', { defaultValue: '' }),
    search_product: I18n.t('search_product', { defaultValue: '' }),
    no_update: I18n.t('no_update', { defaultValue: '' }),
    live_stream: I18n.t('live_stream', { defaultValue: '' }),
    rank_product: I18n.t('rank_product', { defaultValue: '' }),
    require_login_message: I18n.t('require_login_message', {
      defaultValue: '',
    }),
    confirm_logout: I18n.t('confirm_logout', { defaultValue: '' }),
    check_mail: I18n.t('check_mail', { defaultValue: '' }),
    validate_user: I18n.t('validate_user', { defaultValue: '' }),
    input_require_name: I18n.t('input_require_name', { defaultValue: '' }),
    validate_phone_fail: I18n.t('validate_phone_fail', { defaultValue: '' }),
    input_require_password: I18n.t('input_require_password', {
      defaultValue: '',
    }),
    sum_price: I18n.t('sum_price', { defaultValue: '' }),
    order: I18n.t('order', { defaultValue: '' }),
    cart: I18n.t('cart', { defaultValue: '' }),
    code_promotion: I18n.t('code_promotion', { defaultValue: '' }),
    receiver_info: I18n.t('receiver_info', { defaultValue: '' }),
    save: I18n.t('save', { defaultValue: '' }),
    full_name: I18n.t('full_name', { defaultValue: '' }),
    type_name: I18n.t('type_name', { defaultValue: '' }),
    phone: I18n.t('phone', { defaultValue: '' }),
    type_phone: I18n.t('type_phone', { defaultValue: '' }),
    set_address_default: I18n.t('set_address_default', { defaultValue: '' }),
    select: I18n.t('select', { defaultValue: '' }),
    from_library: I18n.t('from_library', { defaultValue: '' }),
    take_photo: I18n.t('take_photo', { defaultValue: '' }),
    total_money: I18n.t('total_money', { defaultValue: '' }),
    payment: I18n.t('payment', { defaultValue: '' }),
    not_update: I18n.t('not_update', { defaultValue: '' }),
    shop: I18n.t('shop', { defaultValue: '' }),
    referral_code: I18n.t('referral_code', { defaultValue: '' }),
    email: I18n.t('email', { defaultValue: '' }),
    type_code: I18n.t('type_code', { defaultValue: '' }),
    type_email: I18n.t('type_email', { defaultValue: '' }),
    type_pass: I18n.t('type_pass', { defaultValue: '' }),
    type_re_pass: I18n.t('type_re_pass', { defaultValue: '' }),
    register: I18n.t('register', { defaultValue: '' }),
    live_streaming: I18n.t('live_streaming', { defaultValue: '' }),
    my_live: I18n.t('my_live', { defaultValue: '' }),
    history_live: I18n.t('history_live', { defaultValue: '' }),
    confirm_close_live: I18n.t('confirm_close_live', { defaultValue: '' }),
    confirm_delete_product: I18n.t('confirm_delete_product', {
      defaultValue: '',
    }),
    ok: I18n.t('ok', { defaultValue: '' }),
    loading: I18n.t('loading', { defaultValue: '' }),
    confirm_close_live_cus: I18n.t('confirm_close_live_cus', {
      defaultValue: '',
    }),
    loading_join_live: I18n.t('loading_join_live', { defaultValue: '' }),
    show: I18n.t('show', { defaultValue: '' }),
    showing: I18n.t('showing', { defaultValue: '' }),
    please_choose_product: I18n.t('please_choose_product', {
      defaultValue: '',
    }),
    sellect_all: I18n.t('sellect_all', { defaultValue: '' }),
    add_product: I18n.t('add_product', { defaultValue: '' }),
    choose_product: I18n.t('choose_product', { defaultValue: '' }),
    time_out_live_shop: I18n.t('time_out_live_shop', { defaultValue: '' }),
    live_not_connect_server: I18n.t('live_not_connect_server', {
      defaultValue: '',
    }),
    delete_product_success: I18n.t('delete_product_success', {
      defaultValue: '',
    }),
    app_crash: I18n.t('app_crash', { defaultValue: '' }),
    please_report: I18n.t('please_report', { defaultValue: '' }),
    restart_app: I18n.t('restart_app', { defaultValue: '' }),
    end_live: I18n.t('end_live', { defaultValue: '' }),
    err_live: I18n.t('err_live', { defaultValue: '' }),
  }
}
export default strings
