// Generated by https://quicktype.io

import { Source } from 'react-native-fast-image';

// LiveStremItemProps
export interface LiveStremItemProps {
  thumbnail_url: null
  cover_image_url: string
  id: number
  user_id: number
  shop_id: number
  title: string
  livestream_record_url: null
  count_viewed: number
  count_reaction: number
  count_comment: number
  start_at: null
  finish_at: null
  expire_at: null
  status: number
  is_active: number
  create_at: string
  update_at: string
  app_id: string
  token_publisher: string
  LivestreamProducts: any[]
  LivestreamLayouts: any[]
}

// Generated by https://quicktype.io

export interface CategotyParentItemProps {
  icon_url: string
  id: number
  name: string
  order: number
  children_category: ChildrenCategory[]
}

export interface ChildrenCategory {
  id: number
  name: string
  order: number
}

export interface propsBottomModal {
  loadingModal?: boolean
  LivestreamProducts?: []
  isShop?: boolean
  showButtonAddProduct?: boolean
  isPreview?: boolean
  itemProduct?: any
  onChangeCode?: (code: string, item: any) => void
  onPressPostProduct?: (item: any) => void
  onPressAddCart?: (item: any) => void
  onPressUpdateCode?: (item: any) => void
  socket?: any
  channelId?: any
  livestream_id?: any
  shopId?: any
}

export interface propsItemListProduct {
  item: any
  index: number
  onChangeTextCode: (code: string) => void
  onPressDeleteProduct: () => void
  onPressImgProduct: () => void
  onPressUpdateCodeItem: () => void
  onFocusInputCode: () => void
}
export interface propsItemListProductCart {
  item: any
  index: number
  onPressImgProduct: () => void
  onPressShowProduct: () => void
  onPressAddCart: () => void
  type: number | undefined
  itemProduct?: any
  isPreview?: boolean
  isShop?: boolean
}

// Generated by https://quicktype.io

export interface ItemCommentWatching {
  id: number
  user_id: number
  shop_id: number
  post_id: null
  livestream_id: number
  parent_id: null
  target_user_id: null
  content: string
  count_like: number
  count_comment: number
  is_active: number
  create_at: string
  update_at: string
  delete_at: null
  is_reaction: number
  count_sub_comment: number
  User: User
  target_user: null
  Shop: Shop
  Comments: any[]
}

export interface Shop {
  profile_picture_url: null
  id: number
  name: string
  phone: string
  pancake_shop_key: string
  pancake_shop_id: string
  stream_minutes_available: number
  agora_project_id: string
  agora_app_id: string
  agora_app_certificate: string
  email: string
  livestream_enable: number
  status: number
  is_active: number
  create_at: string
  update_at: string
  delete_at: null
}

export interface User {
  profile_picture_url: string
  id: number
  shop_id: number
  df_type_user_id: number
  user_name: string
  app_token: string
  last_login_date: string
  device_id: string
  name: string
  phone: string
  email: string
  referal_customer_id: null
  point: number
  status: number
  date_of_birth: string
  gender: null
  is_active: number
  create_at: string
  update_at: string
  delete_at: null
}
export interface propsBottomModal {
  loadingModal?: boolean
  data?: object[]
  isVisible?: boolean
  isShop?: boolean
  isPreview?: boolean
  titleList?: string
  itemProduct?: any
  refToast?: any
  livestream_id?: any
  onBackdropPress?: () => void
  actionAddProduct?: () => void
  handleDeleteProduct?: (item: any) => void
  onChangeCode?: (code: string, item: any) => void
  onPressPostProduct?: (item: any) => void
  onPressAddCart?: (item: any) => void
}

export interface propsHeaderLive {
  isPreview?: boolean
  userNameLive: string
  imgShop: Source | null
  imageProductSell?: string
  onPressCloseLive?: () => void
  onPressProductSell?: () => void
  onPressReload?: () => void
  socket?: any
  count_subcriber: any
  highlightProduct?: any
  channelId?: any
  isShop?: any
  shopId?: any
  LivestreamProducts?: any
  livestream_id?: any
}
