import { Dimensions, Platform, StyleSheet } from 'react-native'
import R from '@app/assets/R'
import { fonts, styleView } from '@app/theme'
import {
  getBottomSpace,
  getStatusBarHeight,
  isIphoneX,
} from 'react-native-iphone-x-helper'

const { width, height } = Dimensions.get('window')
const scale = width / 375

export default StyleSheet.create({
  main: {
    flex: 1,
    backgroundColor: '#F1F3F5',
  },
  viewContent: {
    backgroundColor: 'transparent',
    width: '100%',
    marginTop: 15 * scale,
    zIndex: 9999,
    position: 'absolute',
    top: 48 * scale,
    alignSelf: 'center',
  },
  viewHeader: {
    // ...styleView.rowItemBetween,
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'flex-end',
    paddingHorizontal: 15,
    position: 'absolute',
    width: '100%',
    top: 0,
    height:
      getStatusBarHeight() +
      (Platform.OS == 'android' ? 30 : !isIphoneX() ? 55 : 60),
    zIndex: 1,
    paddingBottom: 10,
  },
  btnGoBack: {
    width: 36 * scale,
    height: 36 * scale,
    borderRadius: 18 * scale,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imgGoBack: { width: 24 * scale, height: 24 * scale },
  viewContentBuy: {
    flexDirection: 'row',
    // marginRight: 7 * scale,
    width: 84 * scale,
    height: 36 * scale,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  viewMainBuy: {
    width: 36 * scale,
    height: 36 * scale,
    backgroundColor: 'rgba(0,0,0,0.08)',
    borderRadius: 18 * scale,
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewIconHeart: {
    width: 36 * scale,
    height: 36 * scale,
    backgroundColor: 'rgba(0,0,0,0.08)',
    borderRadius: 18 * scale,
    justifyContent: 'center',
    alignItems: 'center',
  },
  wrapper: {
    backgroundColor: '#F1F3F5',
    height: 375 * scale,
  },
  viewNameProduct: {
    flexDirection: 'row',
    width: 345 * scale,
    alignSelf: 'center',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 14 * scale,
    backgroundColor: 'white',
  },
  txtNameProduct: {
    fontFamily: R.fonts.sf_regular,
    fontWeight: '500',
    fontSize: 16 * scale,
    color: '#262626',
    fontStyle: 'normal',
    lineHeight: 24 * scale,
  },
  txtPrice: {
    fontFamily: R.fonts.sf_regular,
    fontWeight: '500',
    fontSize: 16 * scale,
    color: '#F03E3E',
    fontStyle: 'normal',
    lineHeight: 24 * scale,
    marginTop: 12 * scale,
    marginLeft: 15 * scale,
  },
  // viewLine: {
  //   borderWidth: 1 * scale,
  //   borderColor: '#F1F3F5',
  //   width: '100%',
  //   marginTop: 12 * scale,
  // },
  viewStar: {
    width: '100%',
    height: 40 * scale,
    marginTop: 1 * scale,
    borderColor: '#F1F3F5',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  txtSelect: {
    fontSize: 16 * scale,
    color: '#69747E',
    fontFamily: R.fonts.sf_regular,
  },
  viewStarContent: {
    width: 345 * scale,
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
  },
  viewStarContent2: {
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
  },
  icon_right: { width: 20 * scale, height: 20 * scale },
  icon_star: { width: 18 * scale, height: 18 * scale, marginRight: 4 * scale },
  txtValue: {
    fontSize: 14 * scale,
    lineHeight: 22 * scale,
    color: '#595959',
    fontFamily: R.fonts.sf_regular,
    fontStyle: 'normal',
    padding: 4 * scale,
  },
  viewChoise: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 335 * scale,
    alignSelf: 'center',
    marginTop: 12 * scale,
  },
  imgSlide: {
    width: width,
    height: 375 * scale,
  },
  txtChoise: {
    fontSize: 16 * scale,
    lineHeight: 24 * scale,
    color: '#595959',
    fontFamily: R.fonts.sf_regular,
    fontWeight: '500',
    fontStyle: 'normal',
  },
  txtChoise2: {
    fontSize: 14 * scale,
    lineHeight: 22 * scale,
    color: '#69747E',
    fontFamily: R.fonts.sf_semi_bold,
    fontStyle: 'normal',
    marginLeft: 10 * scale,
  },
  viewImgProduct: {
    marginTop: 16 * scale,
    flexDirection: 'row',
    width: 335 * scale,
    alignSelf: 'center',
    alignItems: 'center',
    // justifyContent: 'space-between',
    backgroundColor: 'white',
    paddingBottom: 16 * scale,
  },
  txtTittleDetail: {
    fontFamily: R.fonts.sf_regular,
    // marginLeft: 20 * scale,
    marginTop: 12 * scale,
    fontStyle: 'normal',
    fontSize: 16 * scale,
    lineHeight: 24 * scale,
    color: '#595959',
  },
  viewDetail: {
    // height: 50 * scale,
    // backgroundColor: '#F1F3F5',
    width: '100%',
    // marginTop: 12 * scale,
    justifyContent: 'flex-start',
    // marginBottom: 12 * scale,
  },
  viewProduct: {
    width: '100%',
    height: 267 * scale,
    marginTop: 12 * scale,
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewProductMain: {
    width: 345 * scale,
    height: 245 * scale,
    alignSelf: 'center',
  },
  viewImage: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  imgProductDetail: {
    width: 171 * scale,
    height: 171 * scale,
    borderRadius: 5 * scale,
  },
  viewProductDes: {
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10 * scale,
    flexDirection: 'row',
  },
  txtTitleDes: {
    fontStyle: 'normal',
    fontSize: 18 * scale,
    lineHeight: 24 * scale,
    color: '#373E50',
    fontFamily: R.fonts.sf_regular,
  },
  txtPriceDes: {
    fontStyle: 'normal',
    fontSize: 18 * scale,
    lineHeight: 24 * scale,
    color: '#E84343',
    fontFamily: R.fonts.sf_regular,
  },
  txtTotalShell: {
    fontStyle: 'normal',
    fontSize: 16 * scale,
    lineHeight: 22 * scale,
    color: '#69747E',
    fontFamily: R.fonts.sf_regular,
  },
  viewProduct3img: {
    width: 375 * scale,
    height: 325 * scale,
    backgroundColor: 'white',
    marginTop: 10 * scale,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewProduct3img_main: {
    width: 345 * scale,
    height: 305 * scale,
    alignSelf: 'center',
    backgroundColor: 'white',
  },
  viewImage3: {
    width: '100%',
    height: 229 * scale,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  txtBuyNow: {
    fontStyle: 'normal',
    fontSize: 16 * scale,
    lineHeight: 24 * scale,
    color: '#FFFFFF',
    fontWeight: '500',
    fontFamily: R.fonts.sf_regular,
  },
  btnChat_Cart: {
    width: 94 * scale,
    height: '100%',
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnBuyNow: {
    width: 187 * scale,
    height: '100%',
    backgroundColor: '#F03E3E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconChat_Cart: { width: 28 * scale, height: 28 * scale },
  modal: {
    width: 345 * scale,
    height: 516 * scale,
    borderRadius: 30 * scale,
    backgroundColor: 'white',
    position: 'absolute',
    shadowOpacity: 0.5,
    shadowColor: '#000000',
    alignSelf: 'center',
  },
  modalContent: {
    paddingHorizontal: 15 * scale,
  },
  modalProduct: {
    // height: 60 * scale,
    marginTop: 20 * scale,
    flexDirection: 'row',
    // backgroundColor:'yellow'
  },
  modalNumber: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 12 * scale,
  },
  btnDegrease: {
    width: 32 * scale,
    height: 28 * scale,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ECEBED',
    borderWidth: 1 * scale,
    borderColor: '#ECEBED',
  },
  viewNumber: {
    width: 40 * scale,
    height: 28 * scale,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F1F3F5',
    borderWidth: 1 * scale,
    borderColor: '#ECEBED',
  },
  txtTitleModal: {
    fontSize: 16 * scale,
    fontFamily: R.fonts.sf_regular,
    // lineHeight: 22 * scale,

    paddingHorizontal: 7 * scale,
    paddingVertical: 7 * scale,
  },
  viewLine: {
    borderWidth: 1 * scale,
    borderColor: '#BFBFBF',
    // marginHorizontal:15*scale
    width: 315 * scale,
    // marginTop: 4 * scale,
  },
  viewSize: {
    // width: 39 * scale,
    // height: 40 * scale,
    borderRadius: 10 * scale,
    backgroundColor: '#ECEBED',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 6 * scale,
  },
  viewColor: {
    width: 100 * scale,
    height: 40 * scale,
    borderRadius: 10 * scale,
    backgroundColor: '#ECEBED',
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewColorBlack: {
    // width: 47 * scale,
    // height: 40 * scale,
    borderRadius: 10 * scale,
    backgroundColor: '#ECEBED',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnAddCart: {
    width: 315 * scale,
    height: 50 * scale,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F03E3E',
    marginTop: 15 * scale,
    borderRadius: 16 * scale,
  },
  txtAddCart: {
    fontSize: 16 * scale,
    fontFamily: R.fonts.sf_regular,
    fontWeight: '500',
    lineHeight: 24 * scale,
    color: '#FFFFFF',
  },
  viewTxtInput: {
    width: 200 * scale,
    ...fonts.regular16,
  },
  img20: {
    width: 20 * scale,
    height: 20 * scale,
  },
})
