import { colors, dimensions, fonts, HEIGHT, OS, WIDTH } from '@app/theme'
import { StyleSheet } from 'react-native'
import { isIphoneX } from 'react-native-iphone-x-helper'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontSize: 30,
    marginBottom: 50,
    color: '#333',
  },
  createContainer: {
    width: '90%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  joinContainer: {
    width: '90%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 50,
    paddingTop: 50,
    borderTopWidth: 1,
    borderColor: '#22222255',
  },
  joinChannelInput: {
    backgroundColor: '#cccccc77',
    width: '100%',
    borderRadius: 8,
    padding: 20,
    fontSize: 17,
    textAlign: 'center',
  },
  button: {
    width: '100%',
    marginTop: 15,
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#78b0ff',
  },
  buttonText: {
    color: '#fff',
    fontSize: 20,
  },
  vBtnCreate: {
    position: 'absolute',
    bottom: '12%',
    right: 20,
  },
  vListStream: {
    flex: 1,
    paddingHorizontal: 10,
  },
  vImgScreate: {
    width: 55,
    height: 55,
  },
  vImgBackground: {
    width: dimensions.width - 20,
    height: dimensions.height * 0.4,
    borderRadius: 10,
    overflow: 'hidden',
  },
  imgShadow: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    height: dimensions.height * 0.2,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  vInfoOffStream: {
    position: 'absolute',
    bottom: 0,
    padding: 15,
  },
  vInteractive: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  vInfoStreamming: {
    flexDirection: 'row',
    position: 'absolute',
    top: '5%',
    left: 10,
    borderRadius: 5,
    overflow: 'hidden',
  },
  txtLive: {
    color: 'white',
    backgroundColor: 'red',
    paddingHorizontal: 5,
    paddingVertical: 2,
    ...fonts.regular14,
  },
  vViewing: {
    flexDirection: 'row',
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingHorizontal: 5,
    alignItems: 'center',
  },
  txtCount: { color: colors.white, ...fonts.regular14 },
  imgIcon: { width: 15, height: 15, marginRight: 5 },
  txtStatusLive: { ...fonts.semi_bold18, marginVertical: 16 },
  txtTitleOffStream: { ...fonts.semi_bold18, color: colors.white },
  vReaction: { flexDirection: 'row', alignItems: 'center', marginRight: 20 },
  vIconReact: { width: 25, height: 25 },
  txtReaction: { ...fonts.regular14, marginLeft: 6, color: '#595959' },
  vReactionMyLive: {
    flexDirection: 'row',
    marginTop: 8,
    justifyContent: 'space-between',
    width: '90%',
  },
  txtTime: { ...fonts.regular14, color: '#595959' },
  txtTitle: { ...fonts.semi_bold16 },
  vContent: {
    flex: 1,
    paddingLeft: 15,
    justifyContent: 'space-around',
  },
  vImgPlay: { width: 24, height: 24 },
  vImgLive: {
    width: WIDTH / 4,
    height: WIDTH / 4,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  vItemMyLive: {
    backgroundColor: colors.white,
  },
  vContentMyLive: {
    flexDirection: 'row',
    paddingVertical: 16,
    paddingHorizontal: 15,
  },
  vImgReaction: { width: 20, height: 20 },
  vItemReaction: { flexDirection: 'row', alignItems: 'center' },
  vContentFlat: { paddingBottom: '10%' },
  loadingText: {
    fontSize: 18,
    color: '#222',
  },
  fullscreen: {
    width: dimensions.width,
    height: '100%',
  },
  buttonContainer: {
    flexDirection: 'row',
    position: 'absolute',
    bottom: '1%',
    width: dimensions.width,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  txtStartLive: {
    color: 'white',
    ...fonts.semi_bold16,
  },
  broadcasterVideoStateMessage: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    height: '100%',
    backgroundColor: '#222',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  broadcasterVideoStateMessageText: {
    color: '#fff',
    fontSize: 20,
  },
  vBtnStart: {
    backgroundColor: 'rgba(240, 62, 62, 1)',
    paddingVertical: 14,
    paddingHorizontal: '10%',
    borderRadius: 50,
  },
  vBtnReaction: {
    width: 40,
    height: 40,
  },
  vBtnNext: {
    position: 'absolute',
    bottom: '3%',
    backgroundColor: '#E84343',
    alignSelf: 'center',
    paddingVertical: 15,
    paddingHorizontal: '18%',
    borderRadius: 50,
    alignItems: 'center',
  },
  txtTitleLive: {
    height: 40,
    borderBottomWidth: 1,
    paddingBottom: 5,
    marginTop: 30,
    paddingLeft: 15,
    paddingTop: 0,
    borderBottomColor: '#D0DBEA',
    color: 'black',
    ...fonts.regular16,
    marginBottom: 16,
  },
  vCountProduct: {
    backgroundColor: colors.primary,
    position: 'absolute',
    top: -2,
    right: -5,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 100,
    minHeight: 20,
    minWidth: 20,
    paddingHorizontal: 5,
  },
  activityIndicator: { alignSelf: 'center' },
  vHeaderLive: {
    flexDirection: 'row',
    width: WIDTH,
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    position: 'absolute',
    top: '5%',
  },
  imgCloseLive: {
    width: 35,
    height: 35,
  },
  imgProductSell: {
    width: WIDTH * 0.28,
    height: WIDTH * 0.28,
    borderRadius: 10,
  },
  imgShop: {
    width: 40,
    height: 40,
    borderRadius: 40 / 2,
    // overflow: 'hidden',
  },
  vBtnAddProduct: {
    alignSelf: 'center',
    paddingTop: 10,
    paddingBottom: 5,
  },
  vModal: { justifyContent: 'flex-end', margin: 0, width: WIDTH },
  vContentModal: {
    width: WIDTH,
    height: HEIGHT / 2,
    backgroundColor: colors.white,
  },
  txtTitleModal: {
    ...fonts.semi_bold16,
    paddingVertical: 13,
    paddingLeft: 15,
  },
  vLoadingLiveCus: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  vBtnCloseLoading: { position: 'absolute', top: '6%', right: '5%' },
  vFooterWatching: {
    width: WIDTH,
  },
  vReactionWatching: {
    width: WIDTH,
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: OS == 'ios' ? (isIphoneX() ? 10 : '3%') : 0,
    // paddingBottom: OS == 'ios' ? (isIphoneX() ? '5%' : '3%') : 0,
  },
  vListProductHozi: {
    marginBottom: isIphoneX() ? 10 : 16,
    paddingLeft: 15,
    // paddingRight: 20,
    width: WIDTH - 10,
    paddingTop: 5,
  },
  vBtnItem: {
    marginRight: 12,
    backgroundColor: colors.white,
    borderRadius: 5,
    padding: 5,
    width: WIDTH * 0.7,
  },
  vContentItem: { flexDirection: 'row' },
  imgProductItem: {
    width: WIDTH * 0.2,
    height: WIDTH * 0.2,
    borderRadius: 5,
  },
  txtPriceItem: {
    marginTop: 6,
    width: '100%',
    ...fonts.medium14,
    color: colors.primary,
  },
  vContentText: {
    width: '70%',
    paddingHorizontal: 8,
  },
  txtNameProduct: {
    width: '80%',
    ...fonts.regular14,
  },
  vInputComment: {
    flexDirection: 'row',
    width: '50%',
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: 'rgba(1,1,1,0.2)',
    paddingLeft: 10,
  },
  txtInput: {
    flex: 1,
    overflow: 'hidden',
    paddingLeft: 5,
    color: colors.white,
    ...fonts.medium14,
  },
  btnSendComment: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  imgSendComment: { width: 24, height: 24 },
  vItemListProduct: {
    paddingTop: 16,
    paddingHorizontal: 15,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: '#D0DBEA',
  },
  vTextInputCode: {
    marginLeft: 5,
    ...fonts.regular15,
    width: '90%',
    textAlignVertical: 'top',
    paddingTop: 0,
    paddingBottom: 0,
  },
  btnTrash: {
    padding: 10,
  },
  imgTrash: {
    width: 20,
    height: 20,
    tintColor: colors.primary,
  },
  txtPrice: {
    ...fonts.regular15,
    color: colors.primary,
    marginTop: 8,
  },
  vInputCode: {
    flexDirection: 'row',
    marginTop: 10,
    paddingBottom: 10,
  },
  vValueItem: { marginHorizontal: 15, flex: 1 },
  imgEdit: { width: 20, height: 20 },
  imgProduct: { width: 70, height: 70, borderRadius: 5 },
  vItemProductCart: {
    paddingTop: 16,
    paddingHorizontal: 15,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: '#D0DBEA',
    paddingBottom: 12,
  },
  vBtnShowProduct: {
    alignSelf: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderColor: colors.primary,
  },
  txtShowProduct: { color: colors.primary, ...fonts.regular14 },
  img_add_cart: { width: 32, height: 32 },
  txtNameProductItem: { ...fonts.regular16 },
  vValueProductCart: {
    marginHorizontal: 15,
    flex: 1,
    justifyContent: 'space-between',
    paddingVertical: 5,
  },
  vAction: {
    justifyContent: 'space-between',
    paddingBottom: 5,
    alignItems: 'center',
  },
  vFooterListProduct: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    backgroundColor: colors.white,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -4,
    },
    shadowOpacity: 0.05,
    elevation: 1,
  },
  txtCheckAll: {
    ...fonts.regular16,
    marginLeft: 10,
    color: '#262626',
  },
  imgCheckAll: { width: 22, height: 22 },
  btnAddProductList: {
    backgroundColor: colors.primary,
    padding: 15,
    borderRadius: 50,
  },
  txtAddProduct: { ...fonts.semi_bold16, color: colors.white },
  vCheckAll: { flexDirection: 'row', alignItems: 'center' },
  vChillCate: {
    width: WIDTH,
    borderBottomColor: colors.backgroundColor,
    borderBottomWidth: 2,
  },
  vFlatListChillCate: { width: WIDTH - 20, paddingLeft: 20, paddingRight: 20 },
  vUnderLineTab: { backgroundColor: 'transparent' },
  txtTab: { ...fonts.regular15 },
  vBgTab: { backgroundColor: colors.white },
  vReactionFooterLive: {
    flexDirection: 'row',
    width: WIDTH,
    justifyContent: 'space-around',
    paddingVertical: 10,
    bottom: 0,
    paddingHorizontal: 6,
  },
  vFooterLive: {
    position: 'absolute',
    width: WIDTH,
  },
  vContainWatching: { flex: 1 },
  btnSave: {
    color: colors.primary,
    ...fonts.medium14,
  },
  vHeaderBottomModal: { flexDirection: 'row', alignItems: 'center' },
  vModalSelectType: { margin: 0 },
  imgAddProductBottomModal: { width: WIDTH - 20, height: 50 },
  vItemComment: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  imgUser: { width: 24, height: 24, borderRadius: 24 / 2 },
  vContentComment: {
    flexDirection: 'row',
    backgroundColor: 'rgba(1,1,1,0.2)',
    borderRadius: 20,
    padding: 8,
    marginLeft: 8,
  },
  txtNameUser: { color: colors.white, ...fonts.bold14 },
  vFlatlistComment: {
    height: HEIGHT / 3.5,
    paddingHorizontal: 15,
  },
  vCommentLive: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  vAddProduct: {
    paddingVertical: 13,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F3F3',
  },
  txtListProduct: {
    ...fonts.regular16,
    backgroundColor: '#E5E5E5',
    paddingVertical: 15,
    paddingLeft: 15,
  },
  vItemProducCreateLive: {
    paddingTop: 16,
    paddingHorizontal: 15,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: '#D0DBEA',
  },
  vBtnNextCreateLive: { ...fonts.semi_bold16, color: colors.white },
  inputItem: {
    marginLeft: 5,
    ...fonts.regular15,
    width: '90%',
    textAlignVertical: 'top',
    paddingTop: 0,
    paddingBottom: 0,
  },
  coverFullScreen: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 0,
  },
  youtubeVideo: {
    flex: 0,
    marginHorizontal: 8,
    backgroundColor: 'red',
  },
  liveView: {
    flex: 1,
  },
  coverFullScreenLoading: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 0,
    backgroundColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
    width: WIDTH,
    height: HEIGHT,
  },
  fullscreenVideo: {
    // width: dimensions.width,
    // height: '100%',
    // flex: 1,
    // alignSelf: 'stretch',
    position: 'absolute',
    bottom: 0,
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: 'black',
  },
  statsContainer: {
    position: 'absolute',
    right: 20,
    top: 100,
    backgroundColor: 'rgba(0,0,0,0.5)',
    padding: 8,
  },
  statsText: {
    color: '#f8b537',
    fontWeight: '700',
  },
  vBlurViewEndLive: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnDeleteLive: {
    borderRadius: 50,
    paddingHorizontal: '11%',
    alignItems: 'center',
    paddingVertical: 10,
    borderColor: colors.red,
    borderWidth: 1,
  },
  btnSaveLive: {
    backgroundColor: 'red',
    borderRadius: 50,
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: '11%',
  },
  vBtnLive: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
  },
  vStatistical: { flexDirection: 'row', justifyContent: 'space-between' },
  vContentStatistical: {
    position: 'absolute',
    width: WIDTH * 0.9,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 16,
  },
})
